#database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Use the PostGIS dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect

#Gemini API KEY
gemini.api.key={GEMINI_API_KEY}
#in milliseconds
gemini.api.timeout = 10000