# Production database URL (the actual value is injected from an environment variable)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# In production, Hibernate should only validate the schema, not change it
spring.jpa.hibernate.ddl-auto=validate

# Use the PostGIS dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect

#Gemini API KEY
gemini.api.key={GEMINI_API_KEY}
#in milliseconds
gemini.api.timeout = 10000