spring.datasource.url=jdbc:postgresql://localhost:5432/personfinder
spring.datasource.username=pfdbuser
spring.datasource.password=pf_password_123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
